[project]
name = "sample-databricks-project"
version = "1.0.0"
description = "Sample project for Databricks with uv"
authors = [
    { name = "Peter Paluska", email = "paluskapter@gmail.com" }
]
dependencies = [
    "numpy==2.1.3",
    "pandas==2.2.3",
    "py4j==0.10.9.9",
    "pyarrow==19.0.1",
    "pyspark==4.0.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.1",
    "six==1.16.0",
    "tzdata==2024.1",
]
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Repository = "https://github.com/paluskapter/sample-databricks-project"

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.9",
]

[tool.pytest.ini_options]
addopts = "tests --cov=src/sample_databricks_project"

[tool.ruff]
# PyCharm: Settings | Editor | Inspections | Python | Unresolved references | Ignored references
builtins = ["dbutils", "display", "spark"]
line-length = 120

[tool.ruff.lint]
# Rules, explanations and solutions: https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "ANN002", "ANN003", "ANN401", # not required special type annotations disabled
    "BLE", # blind except allowed
    "D100", "D104", "D203", "D212", # unnecessary or conflicting docstyle checks disabled
    "EM", # error message formatting allowed
    "EXE", # shebang not required
    "FIX", # comments for future work allowed
    "I001", # Import sorting disabled until configuration is available: https://github.com/astral-sh/ruff/issues/2600
    "FBT", # bool args allowed
    "G004", # logging f-string allowed
    "PLR2004", # allow magic values
    "PTH123", # built-in open allowed
    "TD002", "TD003", # future work formatting
    "TRY003", # exception messages allowed
]

[tool.ruff.lint.extend-per-file-ignores]
"src/databricks_notebooks/**/*.py" = [
    "E501", # long lines allowed
    "ERA", # commented out code allowed
    "S101", # asserts allowed
    "T20", # print allowed
]
"tests/**/test_*.py" = [
    "D101", "D102", "D103", # docstrings not required
    "S101", # asserts allowed
]

[tool.uv.build-backend]
wheel-exclude = ["databricks_notebooks"]
